<?php

/**
 * @file
 * TODO: Rework module description
 */

/**
* Implementation of hook_requirements().
*/
function spatial_shapefile_requirements($phase) {
  $requirements = array();
  $t = get_t();

  // Check that php zip library is installed
  if (class_exists('ZipArchive')) {
    $requirements['php_zip'] = array(
      'title' => $t('php zip extension'),
      'value' => $t('php zip extension is loaded'),
      'severity' => REQUIREMENT_OK,
    );
  }
  else {
    $requirements['php_zip'] = array(
      'title' => $t('php zip extension'),
      'value' => $t('The php zip extension was not found. Shapefiles cannot be extracted from zip files'),
      'severity' => REQUIREMENT_ERROR,
    );
  }

  return $requirements;
}

/**
* Open a stream to a Shapefile
*/
function spatial_shapefile_open($uri) {
  module_load_include('inc', 'spatial_shapefile', 'spatial_shapefile.class');
  if ($shapefile = new SpatialShapefile($uri)) {
    return $shapefile;
  }
}

function spatial_shapefile_get_wkt($shapefile_uri) {
  if ($shapefile = spatial_shapefile_open($shapefile_uri)) {
    if ($spatial_features = $shapefile->process()) {
      return $spatial_features;
    }
  }

  return NULL;
}

